# собираем образ с именем dev-env каждый раз, когда происходит любое изменение в папке
docker_build(
    'dev-env',
    '.',
    dockerfile='Dockerfile',
    live_update=[
        fall_back_on('.')
    ]
)

# собираем специйикации с помощью kustomize и применяем их
k8s_yaml(kustomize('./kustomize'))

# проброc портов для deployment
k8s_resource('kustomize-test', port_forwards=8080)