apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-test
spec:
  template:
    spec:
      containers:
        - name: kustomize-test
          env:
          - name: FOO
            value: patch